### ISSUE TITLE
Having build issue for Storyboard with latest Xcode

### ISSUE THREAD

**Issue by allnash** [Codeido/PMSuperButton#10]
You can find more about it here.

https://stackoverflow.com/questions/39732312/xcode-8-ib-designables-failed-to-render-and-update-auto-layout-status-the-a

**Comment by allnash** [comment]
Ok...

So this only happens after Apple's PHENOMENAL(release and break shit update) of 
`Xcode version - Version 9.4 (9F1027a)`.

Please see this -->
https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098

I added the following at the end of my Podfile which fixed it.

```# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end```

**Comment by pmusolino** [comment]
Thanks for sharing!

**Comment by patopipp** [comment]
Hey! This solution worked for me!
