### ISSUE TITLE
Method myButton.showLoader() does not hide text while loading

### ISSUE THREAD

**Issue by patopipp** [Codeido/PMSuperButton#11]
I'm trying to use the method showLoader(), the loader appears and spins but the text does not hide as shown in the example in the first part of https://github.com/pmusolino/PMSuperButton.

**Comment by pmusolino** [comment]
Try to set the button as Custom Type in Storyboard and let me know 👍

**Comment by patopipp** [comment]
Thanks! Setting the button as Custom Type fixed my problem!
