### ISSUE TITLE
Adding file manually to project results in build errors

### ISSUE THREAD

**Issue by wousser** [Codeido/PMSuperButton#15]
Add file manually to project

The following errors appear for each open var:
Overriding declaration requires an 'override' keyword
Overriding non-open var outside of its defining module

xcode: Version 10.1 (10B61)
swift: version 4.2.1

**Comment by pmusolino** [comment]
Hi there. Sorry for the delay, I have lost the notification regarding your problem.
Did you solve?

**Comment by pmusolino** [comment]
Closed due to inactivity.
