### ISSUE TITLE
Feature Suggest: Haptic Feedback

### ISSUE THREAD

**Issue by gokulnair2001** [Codeido/PMSuperButton#25]
Hi @pmusolino I saw your framework PMSuperButton, its quite interesting. I know this repo had been inactive for a bit long, but why not provide it a new life. Actually I am really interested in contribution into the repo. I have an amazing feature for your PMSuperButton. With the immense improvement in UX Apple brought ***Haptic Feedback*** into their phones, so why not use that exceptional feature into your framework. It will be really amazing. This small piece of addition will really help to advance your framework. 

With this we can start redesigning this framework. We can add various new features which this framework is lagging. So if you are interested in adding Haptic Feedback do tell me, I will create a PR and Push the file. 

Do give a response, this will help me to know the status, so that I can work further on this project.

I have the code ready, ts just your approval and I can make an PR.

**Comment by pmusolino** [comment]
Hey @gokulnair2001 the project is still active and maintained, but since it's a button component, there is not so much work to do here ;) feel free to open a PR.

**Comment by gokulnair2001** [comment]
Thank you @pmusolino , will soon push a PR :) .
