### ISSUE TITLE
Rounded button with shadow and gradient

### ISSUE THREAD

**Issue by niorko** [Codeido/PMSuperButton#6]
Rounded button with shadow and gradient doesn't show up properly.

<img width="256" alt="obrazok aplikacie spravy 2134338174" src="https://user-images.githubusercontent.com/1008623/31322003-e9da0f1c-ac8e-11e7-8515-e84c47b307a4.png">

If I set clipToBounds to true, button is rounded, but shadow disappears (obviously).

**Comment by pmusolino** [comment]
Good observation. If you have any suggestion to solve this problem feel free to open a PR

**Comment by niorko** [comment]
@Codeido I have just created the quick fix (PR) for the issue.
